version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      # All official @docusaurus/* packages should have the exact same version as @docusaurus/core.
      # From https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups:
      # "You cannot apply a single grouping set of rules to both version updates and security
      # updates [...] you must define two, separately named, grouping sets of rules"
      # See https://github.com/badges/shields/issues/10242 for more information.
      docusaurus-version-updates:
        applies-to: version-updates
        patterns:
          - '@docusaurus/*'
      docusaurus-security-updates:
        applies-to: security-updates
        patterns:
          - '@docusaurus/*'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
